apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: longhorn-basic-auth
  namespace: longhorn-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: longhorn-basic-auth
    creationPolicy: Owner
  data:
    - secretKey: users
      remoteRef:
        key: secret/data/kubernetes/longhorn
        property: htpasswd
