apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 30m
  chart:
    spec:
      chart: longhorn
      version: "1.8.x"
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: longhorn-system
      interval: 12h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: DaemonSet
              name: longhorn-manager
            patch: |
              - op: add
                path: /spec/template/spec/containers/0/resources
                value:
                  requests:
                    cpu: 50m
                    memory: 256Mi
                  limits:
                    cpu: 200m
                    memory: 512Mi
          - target:
              kind: Deployment
              name: longhorn-ui
            patch: |
              - op: add
                path: /spec/template/spec/containers/0/resources
                value:
                  requests:
                    cpu: 10m
                    memory: 64Mi
                  limits:
                    cpu: 100m
                    memory: 128Mi
          - target:
              kind: Deployment
              name: csi-attacher
            patch: |
              - op: add
                path: /spec/template/spec/containers/0/resources
                value:
                  requests:
                    cpu: 10m
                    memory: 64Mi
                  limits:
                    cpu: 100m
                    memory: 128Mi
          - target:
              kind: Deployment
              name: csi-provisioner
            patch: |
              - op: add
                path: /spec/template/spec/containers/0/resources
                value:
                  requests:
                    cpu: 10m
                    memory: 64Mi
                  limits:
                    cpu: 100m
                    memory: 128Mi
          - target:
              kind: Deployment
              name: csi-resizer
            patch: |
              - op: add
                path: /spec/template/spec/containers/0/resources
                value:
                  requests:
                    cpu: 10m
                    memory: 64Mi
                  limits:
                    cpu: 100m
                    memory: 128Mi
          - target:
              kind: Deployment
              name: csi-snapshotter
            patch: |
              - op: add
                path: /spec/template/spec/containers/0/resources
                value:
                  requests:
                    cpu: 10m
                    memory: 64Mi
                  limits:
                    cpu: 100m
                    memory: 128Mi
  values:
    # Default settings
    defaultSettings:
      defaultReplicaCount: 2
      defaultDataPath: /var/lib/longhorn
      guaranteedEngineManagerCPU: 12
      guaranteedReplicaManagerCPU: 12
      storageOverProvisioningPercentage: 100
      storageMinimalAvailablePercentage: 15
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
      # Backup target (can be configured later for NFS)
      # backupTarget: nfs://192.168.2.x:/backup/longhorn
      # NOTE: Resource limits for Longhorn components are set via Kustomize patches
      # See patch-*-resources.yaml files in this directory

    persistence:
      defaultClass: true
      defaultClassReplicaCount: 2
      defaultFsType: ext4
      reclaimPolicy: Delete

    # Ingress for UI
    ingress:
      enabled: true
      ingressClassName: traefik
      host: longhorn.bsdserver.nl
      tls: true
      tlsSecret: longhorn-tls
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        traefik.ingress.kubernetes.io/router.middlewares: longhorn-system-longhorn-basic-auth@kubernetescrd

    # Longhorn manager - exclude control-plane nodes using affinity
    longhornManager:
      nodeSelector:
        kubernetes.io/os: linux
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist

    # CSI driver settings
    csi:
      kubeletRootDir: /var/lib/kubelet

    # Longhorn driver - exclude control-plane nodes
    longhornDriver:
      nodeSelector:
        kubernetes.io/os: linux
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist

    # Longhorn UI - exclude control-plane nodes
    longhornUI:
      nodeSelector:
        kubernetes.io/os: linux
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist

    # Metrics and ServiceMonitor for Prometheus
    metrics:
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: kube-prometheus-stack
