apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-snapshotter
  namespace: longhorn-system
spec:
  template:
    spec:
      containers:
        - name: csi-snapshotter
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
