apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nexus-registry-credentials
  namespace: wbyc-website
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: nexus-registry-credentials
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {"auths":{"nexus.bsdserver.nl:443":{"username":"{{ .username }}","password":"{{ .password }}","auth":"{{ printf "%s:%s" .username .password | b64enc }}"}}}
  data:
    - secretKey: username
      remoteRef:
        key: secret/data/nexus/cicd
        property: username
    - secretKey: password
      remoteRef:
        key: secret/data/nexus/cicd
        property: password
