apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: synology-csi-client-info
  namespace: synology-csi
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: synology-csi-client-info
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        client-info.yml: |
          clients:
            - host: {{ .host }}
              port: 5001
              https: true
              username: {{ .username }}
              password: {{ .password }}
  data:
    - secretKey: host
      remoteRef:
        key: secret/data/kubernetes/synology-csi
        property: host
    - secretKey: username
      remoteRef:
        key: secret/data/kubernetes/synology-csi
        property: username
    - secretKey: password
      remoteRef:
        key: secret/data/kubernetes/synology-csi
        property: password
