apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: synology-csi
  namespace: synology-csi
spec:
  interval: 30m
  chart:
    spec:
      chart: deploy/helm
      sourceRef:
        kind: GitRepository
        name: synology-csi
        namespace: synology-csi
      interval: 12h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Client info secret created via ExternalSecret
    clientInfoSecret:
      name: synology-csi-client-info

    # Controller settings - actual usage: 2m CPU, 152Mi memory
    controller:
      replicaCount: 1
      resources:
        requests:
          cpu: 10m
          memory: 128Mi
        limits:
          cpu: 100m
          memory: 256Mi

    # Node plugin - runs on worker nodes only - actual usage: 0-1m CPU, 45-51Mi memory
    node:
      nodeSelector:
        kubernetes.io/os: linux
      tolerations: []
      resources:
        requests:
          cpu: 5m
          memory: 48Mi
        limits:
          cpu: 50m
          memory: 96Mi
