apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nexus-credentials
  namespace: nexus
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: nexus-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: secret/data/nexus
        property: username
    - secretKey: password
      remoteRef:
        key: secret/data/nexus
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nexus-keycloak
  namespace: nexus
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: nexus-keycloak
    creationPolicy: Owner
    template:
      data:
        client-id: "{{ .client_id }}"
        client-secret: "{{ .client_secret }}"
        # oauth2-proxy requires a 16, 24, or 32 byte cookie secret (base64 encoded)
        cookie-secret: "{{ .cookie_secret }}"
  data:
    - secretKey: client_id
      remoteRef:
        key: secret/data/kubernetes/nexus-oidc
        property: oidc_client_id
    - secretKey: client_secret
      remoteRef:
        key: secret/data/kubernetes/nexus-oidc
        property: oidc_client_secret
    - secretKey: cookie_secret
      remoteRef:
        key: secret/data/kubernetes/nexus-oidc
        property: cookie_secret
