apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nexus-credentials
  namespace: nexus
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: nexus-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: secret/data/nexus
        property: username
    - secretKey: password
      remoteRef:
        key: secret/data/nexus
        property: password
