apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pg-backup-minio-credentials
  namespace: pg-backup
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: pg-backup-minio-credentials
  data:
    - secretKey: MINIO_ACCESS_KEY
      remoteRef:
        key: secret/kubernetes/pg-backup
        property: access-key-id
    - secretKey: MINIO_SECRET_KEY
      remoteRef:
        key: secret/kubernetes/pg-backup
        property: secret-access-key
