apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-db-password
  namespace: pg-backup
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: gitea-db-password
  data:
    - secretKey: password
      remoteRef:
        key: secret/data/gitea
        property: db_password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-db-password
  namespace: pg-backup
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: keycloak-db-password
  data:
    - secretKey: password
      remoteRef:
        key: secret/data/keycloack
        property: kc_db_password
