apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: homepage
spec:
  interval: 30m
  chart:
    spec:
      chart: homepage
      version: "2.x"
      sourceRef:
        kind: HelmRepository
        name: jameswynn
        namespace: homepage
      interval: 12h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: ghcr.io/gethomepage/homepage
      tag: latest

    # Enable Kubernetes integration
    enableRbac: true

    serviceAccount:
      create: true
      name: homepage

    # Ingress
    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - host: homepage.bsdserver.nl
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: homepage-tls
            hosts:
              - homepage.bsdserver.nl

    # Environment variables
    env:
      - name: HOMEPAGE_ALLOWED_HOSTS
        value: homepage.bsdserver.nl

    # Configuration
    config:
      bookmarks:
        - Developer:
            - GitHub:
                - abbr: GH
                  href: https://github.com/pderuiter
                  icon: si-github
            - Gitea:
                - abbr: GT
                  href: https://gitea.bsdserver.nl
                  icon: gitea.png

        - Kubernetes Docs:
            - Kubernetes:
                - abbr: K8s
                  href: https://kubernetes.io/docs/
                  icon: kubernetes.png
            - Flux:
                - abbr: FX
                  href: https://fluxcd.io/docs/
                  icon: flux-cd.png
            - Longhorn:
                - abbr: LH
                  href: https://longhorn.io/docs/
                  icon: longhorn.png
            - CloudNativePG:
                - abbr: PG
                  href: https://cloudnative-pg.io/documentation/
                  icon: postgresql.png

        - HashiCorp Docs:
            - Terraform:
                - abbr: TF
                  href: https://developer.hashicorp.com/terraform/docs
                  icon: terraform.png
            - Vault:
                - abbr: VT
                  href: https://developer.hashicorp.com/vault/docs
                  icon: vault.png
            - Consul:
                - abbr: CS
                  href: https://developer.hashicorp.com/consul/docs
                  icon: consul.png
            - Packer:
                - abbr: PK
                  href: https://developer.hashicorp.com/packer/docs
                  icon: packer.png

        - Ansible Docs:
            - Ansible:
                - abbr: AN
                  href: https://docs.ansible.com/ansible/latest/
                  icon: ansible.png
            - Execution Environments:
                - abbr: EE
                  href: https://ansible.readthedocs.io/en/latest/getting_started_ee/
                  icon: ansible.png
            - Event-Driven Ansible:
                - abbr: EDA
                  href: https://ansible.readthedocs.io/projects/rulebook/
                  icon: ansible.png

        - Network & Storage Docs:
            - Traefik:
                - abbr: TK
                  href: https://doc.traefik.io/traefik/
                  icon: traefik.png
            - HAProxy:
                - abbr: HA
                  href: https://www.haproxy.com/documentation/
                  icon: haproxy.png
            - Gitea:
                - abbr: GT
                  href: https://docs.gitea.com/
                  icon: gitea.png

      services:
        - Infrastructure:
            - Traefik:
                href: https://traefik.bsdserver.nl
                icon: traefik.png
                description: Ingress Controller
                widget:
                  type: traefik
                  url: http://traefik-api.traefik.svc:8080

            - Longhorn:
                href: https://longhorn.bsdserver.nl
                icon: longhorn.png
                description: Distributed Storage
                widget:
                  type: longhorn
                  url: http://longhorn-frontend.longhorn-system.svc:80

            - Vault:
                href: https://192.168.2.170:8200
                icon: vault.png
                description: Secrets Management

            - MinIO:
                href: https://minio-console.bsdserver.nl
                icon: minio.png
                description: Object Storage

            - Keycloak:
                href: https://keycloak.bsdserver.nl
                icon: keycloak.png
                description: Identity & Access Management

            - Netbird:
                href: https://vpn.bsdserver.nl
                icon: netbird.png
                description: VPN & Network Security

            - phpIPAM:
                href: https://ipam.bsdserver.nl
                icon: phpipam.png
                description: IP Address Management

            - Consul:
                href: https://wbyc-srv-docker01.bsdserver.lan:8501/
                icon: consul.png
                description: Service Discovery & Config

        - Monitoring:
            - Grafana:
                href: https://grafana.bsdserver.nl
                icon: grafana.png
                description: Dashboards & Visualization

            - Prometheus:
                href: https://prometheus.bsdserver.nl
                icon: prometheus.png
                description: Metrics Database

            - Alertmanager:
                href: https://alertmanager.bsdserver.nl
                icon: alertmanager.png
                description: Alert Routing

            - Ntfy:
                href: https://ntfy.bsdserver.nl
                icon: ntfy.png
                description: Push Notifications

        - Applications:
            - Ghost:
                href: https://blog.bsdserver.nl
                icon: ghost.png
                description: Blog Platform

            - Gitea:
                href: https://gitea.bsdserver.nl
                icon: gitea.png
                description: Git Server

            - SearXNG:
                href: https://search.bsdserver.nl
                icon: searxng.png
                description: Search Engine

        - DevOps:
            - SonarQube:
                href: https://sonarqube.bsdserver.nl
                icon: sonarqube.png
                description: Code Quality & Security

            - Ansible EDA:
                href: https://eda-ui.bsdserver.nl
                icon: ansible.png
                description: Event-Driven Automation

            - Taiga:
                href: https://taiga.bsdserver.nl
                icon: taiga.png
                description: Project Management

            - n8n:
                href: https://n8n.bsdserver.nl
                icon: n8n.png
                description: Workflow Automation

        - AI & ML:
            - Open WebUI:
                href: https://open-webui.bsdserver.nl
                icon: open-webui.png
                description: LLM Chat Interface

            - Ollama:
                href: https://ollama.bsdserver.nl
                icon: ollama.png
                description: Local LLM Server

            - Qdrant:
                href: https://qdrant.bsdserver.nl
                icon: qdrant.png
                description: Vector Database

        - Tools:
            - ByteStash:
                href: https://snippets.bsdserver.nl
                icon: code.png
                description: Code Snippet Manager

            - Web-Check:
                href: https://webcheck.bsdserver.nl
                icon: web-check.png
                description: Website OSINT Analyzer

        - External:
            - Pangolin:
                href: https://pangolin.bsdserver.nl
                icon: cloudflare-zero-trust.png
                description: Tunnel Gateway (VPS)

      widgets:
        - kubernetes:
            cluster:
              show: true
              cpu: true
              memory: true
              showLabel: true
              label: "Homelab Cluster"
            nodes:
              show: true
              cpu: true
              memory: true
              showLabel: true

        - search:
            provider: google
            target: _blank

        - datetime:
            text_size: xl
            format:
              dateStyle: long
              timeStyle: short
              hour12: false

      kubernetes:
        mode: cluster

      settings:

      settingsString: |
        title: Homelab Dashboard
        favicon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/heimdall.png
        theme: dark
        color: slate
        headerStyle: clean
        layout:
          Infrastructure:
            style: row
            columns: 4
          Monitoring:
            style: row
            columns: 4
          Applications:
            style: row
            columns: 3
          DevOps:
            style: row
            columns: 4
          AI & ML:
            style: row
            columns: 3
          Tools:
            style: row
            columns: 2
          External:
            style: row
            columns: 2

    # Resources
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

    # Schedule on workers
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  operator: DoesNotExist
