apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: homepage
spec:
  interval: 30m
  chart:
    spec:
      chart: homepage
      version: "2.x"
      sourceRef:
        kind: HelmRepository
        name: jameswynn
        namespace: homepage
      interval: 12h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: ghcr.io/gethomepage/homepage
      tag: latest

    # Enable Kubernetes integration
    enableRbac: true

    serviceAccount:
      create: true
      name: homepage

    # Ingress
    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - host: homepage.bsdserver.nl
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: homepage-tls
            hosts:
              - homepage.bsdserver.nl

    # Environment variables
    env:
      - name: HOMEPAGE_ALLOWED_HOSTS
        value: homepage.bsdserver.nl

    # Configuration
    config:
      bookmarks:
        - Developer:
            - GitHub:
                - abbr: GH
                  href: https://github.com/pderuiter
                  icon: si-github
            - Gitea:
                - abbr: GT
                  href: https://gitea.bsdserver.nl
                  icon: gitea.png

        - Documentation:
            - Kubernetes Docs:
                - abbr: K8s
                  href: https://kubernetes.io/docs/
                  icon: kubernetes.png
            - Flux Docs:
                - abbr: FX
                  href: https://fluxcd.io/docs/
                  icon: flux-cd.png

      services:
        - Infrastructure:
            - Traefik:
                href: https://traefik.bsdserver.nl
                icon: traefik.png
                description: Ingress Controller
                widget:
                  type: traefik
                  url: http://traefik-metrics.traefik.svc:9100

            - Longhorn:
                href: https://longhorn.bsdserver.nl
                icon: longhorn.png
                description: Distributed Storage
                widget:
                  type: longhorn
                  url: http://longhorn-frontend.longhorn-system.svc:80

            - Vault:
                href: https://192.168.2.170:8200
                icon: vault.png
                description: Secrets Management

            - MinIO:
                href: https://minio-console.bsdserver.nl
                icon: minio.png
                description: Object Storage

        - Monitoring:
            - Grafana:
                href: https://grafana.bsdserver.nl
                icon: grafana.png
                description: Dashboards & Visualization

            - Prometheus:
                href: https://prometheus.bsdserver.nl
                icon: prometheus.png
                description: Metrics Database

            - Alertmanager:
                href: https://alertmanager.bsdserver.nl
                icon: alertmanager.png
                description: Alert Routing

        - Applications:
            - Ghost:
                href: https://blog.bsdserver.nl
                icon: ghost.png
                description: Blog Platform

            - Gitea:
                href: https://gitea.bsdserver.nl
                icon: gitea.png
                description: Git Server

            - SearXNG:
                href: https://search.bsdserver.nl
                icon: searxng.png
                description: Search Engine

        - External:
            - Pangolin:
                href: https://pangolin.bsdserver.nl
                icon: cloudflare-zero-trust.png
                description: Tunnel Gateway (VPS)
                widget:
                  type: traefik
                  url: http://5.75.184.243:8082

      widgets:
        - kubernetes:
            cluster:
              show: true
              cpu: true
              memory: true
              showLabel: true
              label: "Homelab Cluster"
            nodes:
              show: true
              cpu: true
              memory: true
              showLabel: true

        - search:
            provider: google
            target: _blank

        - datetime:
            text_size: xl
            format:
              dateStyle: long
              timeStyle: short
              hour12: false

      kubernetes:
        mode: cluster

      settings:

      settingsString: |
        title: Homelab Dashboard
        favicon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/heimdall.png
        theme: dark
        color: slate
        headerStyle: clean
        layout:
          Infrastructure:
            style: row
            columns: 4
          Monitoring:
            style: row
            columns: 4
          Applications:
            style: row
            columns: 3
          External:
            style: row
            columns: 2

    # Resources
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

    # Schedule on workers
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  operator: DoesNotExist
