apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: searxng
  namespace: searxng
spec:
  interval: 30m
  chart:
    spec:
      chart: searxng
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: searxng
        namespace: searxng
      interval: 12h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Image configuration
    image:
      repository: searxng/searxng
      tag: latest
      pullPolicy: Always

    # Environment variables
    env:
      INSTANCE_NAME: "WeBuildYourCloud Search"
      BASE_URL: "https://search.bsdserver.nl/"
      AUTOCOMPLETE: "true"

    # Controller
    controller:
      strategy: "RollingUpdate"

    # Service
    service:
      main:
        ports:
          http:
            port: 8080

    # Ingress with TLS
    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - host: search.bsdserver.nl
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: searxng-tls
            hosts:
              - search.bsdserver.nl

    # Persistence for settings
    persistence:
      config:
        enabled: true
        storageClass: longhorn
        size: 1Gi
        accessMode: ReadWriteOnce

    # SearXNG configuration
    searxng:
      config:
        use_default_settings: true
        server:
          # Secret key will be auto-generated if not set
          limiter: false
          image_proxy: true
        ui:
          static_use_hash: true
          default_theme: simple
          infinite_scroll: true
        search:
          safe_search: 0
          autocomplete: "google"
          default_lang: "nl"
        engines:
          # Disable tracking-heavy engines
          - name: google
            disabled: false
          - name: duckduckgo
            disabled: false
          - name: wikipedia
            disabled: false
          - name: bing
            disabled: true
          - name: yahoo
            disabled: true

    # Resources
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi

    # Node affinity - schedule on workers
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  operator: DoesNotExist

    # Optional: Enable Redis for rate limiting and caching
    redis:
      enabled: false
