apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../config/vault-auth
  - metallb
  - ../../config/cert-manager
  - ../../config/external-dns
  # CRD-dependent resources deferred from controllers phase
  - external-dns-transip-externalsecret.yaml
  - traefik-dashboard-ingressroute.yaml
