---
apiVersion: v1
kind: Service
metadata:
  name: unifi-update-exporter
  namespace: unifi
  labels:
    app.kubernetes.io/name: unifi-update-exporter
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: unifi-update-exporter
  ports:
    - name: metrics
      port: 9131
      targetPort: metrics
