---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: unifi
  namespace: unifi
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values:
          - unpoller
          - unifi-update-exporter
  endpoints:
    - port: metrics
      interval: 60s
      scrapeTimeout: 30s
      path: /metrics
