apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: "1.15.x"
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: external-dns
      interval: 12h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # RFC2136 provider for internal BIND DNS
    provider:
      name: rfc2136

    # Environment variables from secret
    extraEnvVarsSecret: rfc2136-credentials

    # RFC2136 specific configuration
    extraArgs:
      - --rfc2136-host=192.168.2.2
      - --rfc2136-port=53
      - --rfc2136-zone=bsdserver.nl
      - --rfc2136-tsig-axfr
      - --rfc2136-insecure=false

    # Domain filter
    domainFilters:
      - bsdserver.nl

    # Policy - sync will create, update, and delete records
    policy: sync

    # Sources to watch
    sources:
      - service
      - ingress

    # TXT record prefix for ownership
    txtOwnerId: "external-dns"
    txtPrefix: "_externaldns."

    # Resource limits
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 100m
        memory: 64Mi

    # Tolerations
    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"

    # Log level
    logLevel: info
