apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-sysctl-tuning
  namespace: kube-system
  labels:
    app: node-sysctl-tuning
spec:
  selector:
    matchLabels:
      app: node-sysctl-tuning
  template:
    metadata:
      labels:
        app: node-sysctl-tuning
    spec:
      hostPID: true
      hostNetwork: true
      initContainers:
        - name: sysctl-tuning
          image: busybox:1.36
          securityContext:
            privileged: true
          command:
            - sh
            - -c
            - |
              echo "Applying sysctl settings for Kubernetes..."

              # Increase inotify limits for file watching (Loki, Alloy, Flux, etc.)
              sysctl -w fs.inotify.max_user_watches=524288
              sysctl -w fs.inotify.max_user_instances=512

              # Write to persistent sysctl config
              cat > /host-etc/sysctl.d/99-kubernetes-tuning.conf << EOF
              # Kubernetes node tuning - applied by node-sysctl-tuning DaemonSet
              # Increase inotify limits for file watching
              fs.inotify.max_user_watches = 524288
              fs.inotify.max_user_instances = 512
              EOF

              echo "Sysctl settings applied successfully"
              cat /host-etc/sysctl.d/99-kubernetes-tuning.conf
          volumeMounts:
            - name: host-etc
              mountPath: /host-etc
      containers:
        - name: pause
          image: gcr.io/google_containers/pause:3.2
          resources:
            requests:
              cpu: 1m
              memory: 1Mi
            limits:
              cpu: 10m
              memory: 10Mi
      volumes:
        - name: host-etc
          hostPath:
            path: /etc
            type: Directory
      tolerations:
        - operator: Exists
          effect: NoSchedule
        - operator: Exists
          effect: NoExecute
