apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: garage-credentials
  namespace: keycloak-backup
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: garage-credentials
  data:
    - secretKey: ACCESS_KEY
      remoteRef:
        key: secret/kubernetes/garage-backup
        property: access-key-id
    - secretKey: SECRET_KEY
      remoteRef:
        key: secret/kubernetes/garage-backup
        property: secret-access-key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-db-password
  namespace: keycloak-backup
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: keycloak-db-password
  data:
    - secretKey: password
      remoteRef:
        key: secret/keycloack
        property: kc_db_password
