apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-credentials
  namespace: keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: keycloak-credentials
    creationPolicy: Owner
  data:
    - secretKey: KC_DB_USERNAME
      remoteRef:
        key: secret/data/keycloack
        property: kc_db_username
    - secretKey: KC_DB_PASSWORD
      remoteRef:
        key: secret/data/keycloack
        property: kc_db_password
    - secretKey: KEYCLOAK_ADMIN
      remoteRef:
        key: secret/data/keycloack
        property: kc_admin_name
    - secretKey: KEYCLOAK_ADMIN_PASSWORD
      remoteRef:
        key: secret/data/keycloack
        property: kc_admin_password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-postgres-credentials
  namespace: keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: keycloak-postgres-credentials
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: secret/data/keycloack
        property: kc_db_username
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: secret/data/keycloack
        property: kc_db_password
