apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: netbird
  namespace: netbird
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: netbird
    creationPolicy: Owner
  data:
    - secretKey: NB_SETUP_KEY
      remoteRef:
        key: secret/data/kubernetes/netbird
        property: setup_key
    - secretKey: NB_MANAGEMENT_URL
      remoteRef:
        key: secret/data/kubernetes/netbird
        property: management_url
