apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-credentials
  namespace: minio
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: minio-credentials
    creationPolicy: Owner
  data:
    - secretKey: rootUser
      remoteRef:
        key: secret/data/kubernetes/minio
        property: root-user
    - secretKey: rootPassword
      remoteRef:
        key: secret/data/kubernetes/minio
        property: root-password
