---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: valkey
  namespace: skool
  labels:
    app.kubernetes.io/name: skool
    app.kubernetes.io/component: valkey
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: skool
      app.kubernetes.io/component: valkey
