apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 30m
  chart:
    spec:
      chart: metallb
      version: "0.14.x"
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: metallb-system
      interval: 12h
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    # IMPORTANT: kube-proxy must have strictARP: true when using IPVS mode.
    # Without it, every node responds to ARP for LoadBalancer IPs (bound to
    # kube-ipvs0), causing traffic to land on nodes without the target pod.
    # This results in intermittent timeouts and blackholed connections.
    #
    # Verify with:
    #   kubectl get configmap kube-proxy -n kube-system -o yaml | grep strictARP
    #
    # Fix with:
    #   kubectl edit configmap kube-proxy -n kube-system  # set strictARP: true
    #   kubectl rollout restart daemonset kube-proxy -n kube-system
    controller:
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 128Mi
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
    speaker:
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 128Mi
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
