apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sonarqube-database
  namespace: sonarqube
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: sonarqube-database
    creationPolicy: Owner
  data:
    - secretKey: SONAR_JDBC_URL
      remoteRef:
        key: secret/data/kubernetes/sonarqube/database
        property: SONAR_JDBC_URL
    - secretKey: SONAR_JDBC_USERNAME
      remoteRef:
        key: secret/data/kubernetes/sonarqube/database
        property: SONAR_JDBC_USERNAME
    - secretKey: SONAR_JDBC_PASSWORD
      remoteRef:
        key: secret/data/kubernetes/sonarqube/database
        property: SONAR_JDBC_PASSWORD
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sonarqube-postgres-credentials
  namespace: sonarqube
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: sonarqube-postgres-credentials
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_DB
      remoteRef:
        key: secret/data/kubernetes/sonarqube/database
        property: POSTGRES_DB
    - secretKey: POSTGRES_USER
      remoteRef:
        key: secret/data/kubernetes/sonarqube/database
        property: POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: secret/data/kubernetes/sonarqube/database
        property: POSTGRES_PASSWORD
