apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-credentials
  namespace: gitea
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: gitea-credentials
    creationPolicy: Owner
  data:
    - secretKey: GITEA__database__NAME
      remoteRef:
        key: secret/data/gitea
        property: db_name
    - secretKey: GITEA__database__USER
      remoteRef:
        key: secret/data/gitea
        property: db_user
    - secretKey: GITEA__database__PASSWD
      remoteRef:
        key: secret/data/gitea
        property: db_password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-postgres-credentials
  namespace: gitea
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: gitea-postgres-credentials
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: secret/data/gitea
        property: db_user
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: secret/data/gitea
        property: db_password
    - secretKey: POSTGRES_DB
      remoteRef:
        key: secret/data/gitea
        property: db_name
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-oidc
  namespace: gitea
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: gitea-oidc
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: secret/data/kubernetes/gitea-oidc
        property: oidc_client_id
    - secretKey: client-secret
      remoteRef:
        key: secret/data/kubernetes/gitea-oidc
        property: oidc_client_secret
    - secretKey: issuer-url
      remoteRef:
        key: secret/data/kubernetes/gitea-oidc
        property: oidc_issuer_url
