apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
  namespace: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: alloy
      version: "0.x"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: observability
      interval: 12h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    alloy:
      configMap:
        content: |
          // Discover Kubernetes pods for log collection
          discovery.kubernetes "pods" {
            role = "pod"
          }

          // Relabel pod logs
          discovery.relabel "pods" {
            targets = discovery.kubernetes.pods.targets

            rule {
              source_labels = ["__meta_kubernetes_namespace"]
              target_label  = "namespace"
            }
            rule {
              source_labels = ["__meta_kubernetes_pod_name"]
              target_label  = "pod"
            }
            rule {
              source_labels = ["__meta_kubernetes_pod_container_name"]
              target_label  = "container"
            }
            rule {
              source_labels = ["__meta_kubernetes_pod_label_app"]
              target_label  = "app"
            }
            rule {
              source_labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_name"]
              target_label  = "app_name"
            }
            rule {
              source_labels = ["__meta_kubernetes_pod_node_name"]
              target_label  = "node"
            }
          }

          // Collect pod logs
          loki.source.kubernetes "pods" {
            targets    = discovery.relabel.pods.output
            forward_to = [loki.write.default.receiver]
          }

          // Collect Kubernetes events as logs
          loki.source.kubernetes_events "events" {
            forward_to = [loki.write.default.receiver]
          }

          // Send logs to Loki
          loki.write "default" {
            endpoint {
              url = "http://loki-gateway.observability.svc:80/loki/api/v1/push"
            }
          }

          // Remote write to Prometheus
          prometheus.remote_write "default" {
            endpoint {
              url = "http://kube-prometheus-stack-prometheus.observability.svc:9090/api/v1/write"
            }
          }

      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi

    controller:
      type: daemonset

    # Need to mount host paths for log collection
    extraMounts:
      - name: varlog
        mountPath: /var/log
        hostPath:
          path: /var/log
          type: Directory
        readOnly: true
      - name: varlibdockercontainers
        mountPath: /var/lib/docker/containers
        hostPath:
          path: /var/lib/docker/containers
          type: Directory
        readOnly: true

    serviceAccount:
      create: true

    # RBAC for Kubernetes discovery
    rbac:
      create: true
---
# Separate Alloy deployment for vSphere metrics (singleton, not daemonset)
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy-vsphere
  namespace: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: alloy
      version: "0.x"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: observability
      interval: 12h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    fullnameOverride: alloy-vsphere

    alloy:
      configMap:
        content: |
          // vSphere exporter - native Alloy component
          prometheus.exporter.vsphere "vcenter" {
            vsphere_url      = "https://" + env("VSPHERE_HOST") + "/sdk"
            vsphere_user     = env("VSPHERE_USER")
            vsphere_password = env("VSPHERE_PASSWORD")

            // Collection settings
            enable_exporter_metrics = true

            // Collect VMs, hosts, and datastores
            vm_metric_include       = ["*"]
            host_metric_include     = ["*"]
            datastore_metric_include = ["*"]

            // Discovery interval
            discovery_interval = "5m"
          }

          // Scrape the vSphere exporter
          prometheus.scrape "vsphere" {
            targets    = prometheus.exporter.vsphere.vcenter.targets
            forward_to = [prometheus.remote_write.default.receiver]

            scrape_interval = "60s"
            scrape_timeout  = "55s"
          }

          // Remote write to Prometheus
          prometheus.remote_write "default" {
            endpoint {
              url = "http://kube-prometheus-stack-prometheus.observability.svc:9090/api/v1/write"
            }
          }

      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi

      # vSphere credentials from secret
      extraEnvFrom:
        - secretRef:
            name: vsphere-credentials

    # Single replica deployment (not daemonset)
    controller:
      type: deployment
      replicas: 1

    # Schedule on worker nodes
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  operator: DoesNotExist

    serviceAccount:
      create: true
