apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
  namespace: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: alloy
      version: "0.x"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: observability
      interval: 12h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    alloy:
      configMap:
        content: |
          // Discover Kubernetes pods for log collection
          discovery.kubernetes "pods" {
            role = "pod"
          }

          // Relabel pod logs
          discovery.relabel "pods" {
            targets = discovery.kubernetes.pods.targets

            rule {
              source_labels = ["__meta_kubernetes_namespace"]
              target_label  = "namespace"
            }
            rule {
              source_labels = ["__meta_kubernetes_pod_name"]
              target_label  = "pod"
            }
            rule {
              source_labels = ["__meta_kubernetes_pod_container_name"]
              target_label  = "container"
            }
            rule {
              source_labels = ["__meta_kubernetes_pod_label_app"]
              target_label  = "app"
            }
            rule {
              source_labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_name"]
              target_label  = "app_name"
            }
            rule {
              source_labels = ["__meta_kubernetes_pod_node_name"]
              target_label  = "node"
            }
          }

          // Collect pod logs
          loki.source.kubernetes "pods" {
            targets    = discovery.relabel.pods.output
            forward_to = [loki.write.default.receiver]
          }

          // Collect Kubernetes events as logs
          loki.source.kubernetes_events "events" {
            forward_to = [loki.write.default.receiver]
          }

          // Send logs to Loki
          loki.write "default" {
            endpoint {
              url = "http://loki-gateway.observability.svc:80/loki/api/v1/push"
            }
          }

          // Remote write to Prometheus
          prometheus.remote_write "default" {
            endpoint {
              url = "http://kube-prometheus-stack-prometheus.observability.svc:9090/api/v1/write"
            }
          }

      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi

    controller:
      type: daemonset

    # Need to mount host paths for log collection
    extraMounts:
      - name: varlog
        mountPath: /var/log
        hostPath:
          path: /var/log
          type: Directory
        readOnly: true
      - name: varlibdockercontainers
        mountPath: /var/lib/docker/containers
        hostPath:
          path: /var/lib/docker/containers
          type: Directory
        readOnly: true

    serviceAccount:
      create: true

    # RBAC for Kubernetes discovery
    rbac:
      create: true
---
# Separate Alloy deployment for vSphere metrics (singleton, not daemonset)
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy-vsphere
  namespace: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: alloy
      version: "0.x"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: observability
      interval: 12h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    fullnameOverride: alloy-vsphere

    alloy:
      # Enable experimental components (required for otelcol.receiver.vcenter)
      extraArgs:
        - --stability.level=experimental

      configMap:
        content: |
          // vSphere metrics collection using OpenTelemetry vCenter receiver
          // This is an experimental component that replaces prometheus.exporter.vsphere
          otelcol.receiver.vcenter "vcenter" {
            endpoint = "https://" + env("VSPHERE_HOST")
            username = env("VSPHERE_USER")
            password = env("VSPHERE_PASSWORD")

            // Skip TLS verification for self-signed certs
            tls {
              insecure_skip_verify = true
            }

            // Collection interval
            collection_interval = "60s"

            output {
              metrics = [otelcol.processor.batch.default.input]
            }
          }

          // Batch processor for efficiency
          otelcol.processor.batch "default" {
            output {
              metrics = [otelcol.exporter.prometheus.default.input]
            }
          }

          // Export metrics in Prometheus format for scraping
          otelcol.exporter.prometheus "default" {
            forward_to = [prometheus.remote_write.default.receiver]
          }

          // Remote write to Prometheus
          prometheus.remote_write "default" {
            endpoint {
              url = "http://kube-prometheus-stack-prometheus.observability.svc:9090/api/v1/write"
            }
          }

      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi

      # vSphere credentials from secret
      extraEnvFrom:
        - secretRef:
            name: vsphere-credentials

    # Single replica deployment (not daemonset)
    controller:
      type: deployment
      replicas: 1

    # Schedule on worker nodes
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  operator: DoesNotExist

    serviceAccount:
      create: true
