apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ntfy
  namespace: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: ntfy
      version: "0.x"
      sourceRef:
        kind: HelmRepository
        name: ntfy
        namespace: observability
      interval: 12h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    replicaCount: 1

    # Resources
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi

    # Persistence
    persistence:
      enabled: true
      storageClass: longhorn
      size: 5Gi

    # Ingress
    ingress:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
      hosts:
        - host: ntfy.bsdserver.nl
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: ntfy-tls
          hosts:
            - ntfy.bsdserver.nl

    # ntfy configuration
    config:
      base-url: https://ntfy.bsdserver.nl
      cache-file: /var/cache/ntfy/cache.db
      cache-duration: 24h
      behind-proxy: true
      keepalive-interval: 45s

    # Affinity
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  operator: DoesNotExist
