apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ntfy
  namespace: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: ntfy
      version: "0.1.x"
      sourceRef:
        kind: HelmRepository
        name: ntfy
        namespace: observability
      interval: 12h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    replicaCount: 1

    image:
      repository: binwiederhier/ntfy
      tag: v2.11.0
      pullPolicy: IfNotPresent

    # Resources
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi

    # Persistence
    persistence:
      enabled: true
      storageClass: longhorn
      size: 5Gi

    # Service
    service:
      type: ClusterIP
      port: 80

    # Ingress
    ingress:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        external-dns.alpha.kubernetes.io/target: 192.168.2.160
      hosts:
        - host: ntfy.bsdserver.nl
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: ntfy-tls
          hosts:
            - ntfy.bsdserver.nl

    # ntfy configuration
    ntfy:
      baseUrl: https://ntfy.bsdserver.nl
      behindProxy: true
      cacheDuration: 24h
      keepaliveInterval: 45s

    # Affinity
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  operator: DoesNotExist
