apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmware-exporter
  namespace: observability
  labels:
    app: vmware-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vmware-exporter
  template:
    metadata:
      labels:
        app: vmware-exporter
    spec:
      containers:
        - name: vmware-exporter
          image: pryorda/vmware_exporter:latest
          ports:
            - containerPort: 9272
              name: metrics
          env:
            - name: VSPHERE_HOST
              valueFrom:
                secretKeyRef:
                  name: vsphere-credentials
                  key: vsphere-host
            - name: VSPHERE_USER
              valueFrom:
                secretKeyRef:
                  name: vsphere-credentials
                  key: vsphere-user
            - name: VSPHERE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vsphere-credentials
                  key: vsphere-password
            - name: VSPHERE_IGNORE_SSL
              value: "True"
            - name: VSPHERE_COLLECT_HOSTS
              value: "True"
            - name: VSPHERE_COLLECT_DATASTORES
              value: "True"
            - name: VSPHERE_COLLECT_VMS
              value: "True"
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9272
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 9272
            initialDelaySeconds: 5
            periodSeconds: 5
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist
---
apiVersion: v1
kind: Service
metadata:
  name: vmware-exporter
  namespace: observability
  labels:
    app: vmware-exporter
spec:
  selector:
    app: vmware-exporter
  ports:
    - port: 9272
      targetPort: 9272
      name: metrics
