apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 1h
  chart:
    spec:
      chart: external-secrets
      version: "0.10.x"  # Will get latest 0.10.x patch version
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: external-secrets
      interval: 24h
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    # Install CRDs with the chart
    installCRDs: true

    # Controller configuration
    replicaCount: 1
    # Performance tuning
    concurrent: 3  # Process 3 secrets concurrently (default: 1)
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi

    # Webhook configuration - DISABLED due to known performance issues
    # The webhook validates CRDs but causes high CPU usage in interaction with cert-controller
    # For homelab use, validation at apply-time is sufficient
    webhook:
      enabled: false

    # Cert controller - DISABLED (not needed without webhook)
    certController:
      enabled: false

    # Service account for Vault Kubernetes auth
    serviceAccount:
      create: true
      name: external-secrets
      annotations: {}
