apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: transip-credentials
  namespace: external-dns-transip
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: transip-credentials
    creationPolicy: Owner
  data:
    - secretKey: TRANSIP_ACCOUNT_NAME
      remoteRef:
        key: dns
        property: transip_login
    - secretKey: private-key
      remoteRef:
        key: dns
        property: transip_private_key
