---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - externalsecrets.yaml
  - db-init-job.yaml
  - redis.yaml
  - api.yaml
  - admin-api.yaml
  - web.yaml
  - realtime.yaml
  - ingress.yaml
