apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-credentials
  namespace: minio
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: minio-credentials
    creationPolicy: Owner
  data:
    - secretKey: MINIO_ROOT_USER
      remoteRef:
        key: secret/data/minio
        property: minio_root_user
    - secretKey: MINIO_ROOT_PASSWORD
      remoteRef:
        key: secret/data/minio
        property: minio_root_password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-oidc
  namespace: minio
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: minio-oidc
    creationPolicy: Owner
    template:
      data:
        MINIO_IDENTITY_OPENID_CLIENT_ID: "{{ .client_id }}"
        MINIO_IDENTITY_OPENID_CLIENT_SECRET: "{{ .client_secret }}"
        MINIO_IDENTITY_OPENID_CONFIG_URL: "{{ .issuer_url }}/.well-known/openid-configuration"
  data:
    - secretKey: client_id
      remoteRef:
        key: secret/data/kubernetes/minio-oidc
        property: oidc_client_id
    - secretKey: client_secret
      remoteRef:
        key: secret/data/kubernetes/minio-oidc
        property: oidc_client_secret
    - secretKey: issuer_url
      remoteRef:
        key: secret/data/kubernetes/minio-oidc
        property: oidc_issuer_url
