apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bytestash-data
  namespace: bytestash
  labels:
    app.kubernetes.io/name: bytestash
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
